# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_articulo.ipynb.

# %% auto 0
__all__ = ['Articulo']

# %% ../nbs/01_articulo.ipynb 3
class Articulo:
    '''
    La clase Articulo representa un artículo en un sistema de gestión de inventario. Aquí tienes una breve descripción:

La clase Articulo tiene los siguientes atributos:

nombre (str): El nombre del artículo.

precio (float): El precio del artículo.

cantidad (int): La cantidad de unidades del artículo en el inventario.

agregado (bool, opcional, por defecto False): Un indicador que representa si el artículo ha sido agregado.

El método __str__ proporciona una representación legible del objeto en formato de cadena, incluyendo el nombre, precio, cantidad y el estado de si fue agregado o no.

La clase se utiliza para modelar y gestionar información sobre artículos en un inventario, proporcionando una manera conveniente de acceder y manipular datos relacionados con el inventario.
'''
    def __init__(self,
                 nombre:str,# nombre del artículo
                 precio:float,# precio del artículo
                 cantidad:int,# cantidad del artículo
                 agregado:bool=False # si fue agregado
                 ) -> None:
        self.nombre = nombre
        self.precio = precio
        self.cantidad = cantidad
        self.agregado = agregado
        
    def __str__(self) -> str:
        "Regresa la informacion completa sobre el articulo en formato String"
        return f'Artículo: {self.nombre} Precio: {self.precio} Cantidad: {self.cantidad} Fue agregado: {self.agregado}'
    __repr__=__str__
