# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core copy.ipynb.

# %% auto 0
__all__ = ['Tienda', 'Articulo', 'listaDeSuper']

# %% ../nbs/00_core copy.ipynb 3
class Tienda:
    
    def __init__(self,
                 titulo:str, # titulo de la tarea
                 fecha_entrega:str, #fecha de entrega de la tarea
                 descripcion:str='', #descripcion de la tarea
                 ) -> None:
        self.titulo = titulo
        self.fecha_entrega = fecha_entrega
        self.descripcion = descripcion
        self.completado = False
    
    def __str__(self) -> str:
        return f'Tarea: {self.titulo} Descripcion:({self.descripcion}) Fecha de entrega: {self.fecha_entrega} Completado: {self.completado}'
    __repr__=__str__

# %% ../nbs/00_core copy.ipynb 8
class Articulo:
    def __init__(self,
                 nombre:str,# nombre del artículo
                 precio:float,# precio del artículo
                 cantidad:int,# cantidad del artículo
                 agregado:bool=False # si fue agregado
                 ) -> None:
        self.nombre = nombre
        self.precio = precio
        self.cantidad = cantidad
        self.agregado = agregado
        
    def __str__(self) -> str:
        return f'Artículo: {self.nombre} Precio: {self.precio} Cantidad: {self.cantidad} Fue agregado: {self.agregado}'
    __repr__=__str__

# %% ../nbs/00_core copy.ipynb 13
class listaDeSuper:
    def __init__(self,
                 articulos:List[Articulo]=None # lista de supermercado
                 ) -> None:
        self.articulos = articulos if articulos else []
        
    def __str__(self) -> str:
        return f'Artículos: {self.articulos}'
    __repr__=__str__
    
    def articuloNoAgregado(self) -> str:
        noAgregados = ''
        for articulo in self.articulos:
            if not articulo.agregado:
                noAgregados += articulo.nombre + ', '
