# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core copy.ipynb.

# %% auto 0
__all__ = ['Tarea']

# %% ../nbs/00_core copy.ipynb 3
class Tarea:
    
    def __init__(self,
                 titulo:str, # titulo de la tarea
                 fecha_entrega:str, #fecha de entrega de la tarea
                 descripcion:str='', #descripcion de la tarea
                 ) -> None:
        self.titulo = titulo
        self.fecha_entrega = fecha_entrega
        self.descripcion = descripcion
        self.completado = False
    
    def __str__(self) -> str:
        return f'Tarea: {self.titulo} Descripcion:({self.descripcion}) Fecha de entrega: {self.fecha_entrega} Completado: {self.completado}'
    __repr__=__str__
